name: curl
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - absl-py
  - pyparsing
  - pillow
  - pip:
    - gym==0.21.0
    - termcolor
    - dm_control
    - gym-dmc
    - mujoco
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - torchvision
    - scikit-image
