name: curl
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - absl-py
  - pyparsing
  - pillow
  - pip:
    - termcolor
    - dm_control
    - git+https://github.com/1nadequacy/dmc2gym.git
    - mujoco
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - torchvision
    - scikit-image
